### ISSUE TITLE
Refactor homebrew install

### ISSUE THREAD

**Issue by a2f0** [a2f0/dotfiles#73]
https://www.nickhammond.com/automating-development-environment-ansible/

example:

```
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - apple-gcc42
        - vim
        - ack
        - git
        - rbenv
        - ruby-build
        - elasticsearch
        - mysql
        - tmux
 ```
